### ISSUE TITLE
Inconsistent Handling of Input Arguments in List Function

### ISSUE THREAD

**Issue by msslr** [LeaseWeb/leaseweb-go-sdk#68]
we noticed that the DedicatedServerApi List function in the provided code is inconsistently handling its input arguments. Specifically, the function accepts multiple arguments of different types and lengths, but it does not provide any clear guidelines on how to use these arguments, and it does not handle them consistently.

To address this issue, I suggest using a struct to store the input options for the List function, as shown in the provided code workaround. This approach provides a more structured and flexible way of handling input options and avoids the issues of inconsistently handling input arguments.

I believe this change will improve the clarity and maintainability of the code and make it easier for developers to use the List function. I welcome any feedback or suggestions on this approach and would appreciate it if the project maintainers could review and consider this change.

Thank you.

```
+type ListOptions struct {
+	Offset                int
+	Limit                 int
+	IP                    string
+	MacAddress            string
+	Site                  string
+	PrivateRackID         string
+	PrivateNetworkCapable bool
+	PrivateNetworkEnabled bool
+}
+
 func (dsa DedicatedServerApi) getPath(endpoint string) string {
 	return "/bareMetals/" + DEDICATED_SERVER_API_VERSION + endpoint
 }
 
-func (dsa DedicatedServerApi) List(args ...interface{}) (*DedicatedServers, error) {
+func (dsa DedicatedServerApi) List(opts ...ListOptions) (*DedicatedServers, error) {
 	v := url.Values{}
-	if len(args) >= 1 {
-		v.Add("offset", fmt.Sprint(args[0]))
-	}
-	if len(args) >= 2 {
-		v.Add("limit", fmt.Sprint(args[1]))
-	}
-	if len(args) >= 3 {
-		v.Add("ip", fmt.Sprint(args[2]))
-	}
-	if len(args) >= 4 {
-		v.Add("macAddress", fmt.Sprint(args[3]))
-	}
-	if len(args) >= 5 {
-		v.Add("site", fmt.Sprint(args[4]))
-	}
-	if len(args) >= 6 {
-		v.Add("privateRackId", fmt.Sprint(args[5]))
-	}
-	if len(args) >= 7 {
-		v.Add("privateNetworkCapable", fmt.Sprint(args[6]))
-	}
-	if len(args) >= 8 {
-		v.Add("privateNetworkEnabled", fmt.Sprint(args[7]))
+	if len(opts) > 0 {
+		opt := opts[0]
+		if opt.Offset > 0 {
+			v.Add("offset", fmt.Sprint(opt.Offset))
+		}
+		if opt.Limit > 0 {
+			v.Add("limit", fmt.Sprint(opt.Limit))
+		}
+		if opt.IP != "" {
+			v.Add("ip", opt.IP)
+		}
+		if opt.MacAddress != "" {
+			v.Add("macAddress", opt.MacAddress)
+		}
+		if opt.Site != "" {
+			v.Add("site", opt.Site)
+		}
+		if opt.PrivateRackID != "" {
+			v.Add("privateRackId", opt.PrivateRackID)
+		}
+		if opt.PrivateNetworkCapable {
+			v.Add("privateNetworkCapable", "true")
+		}
+		if opt.PrivateNetworkEnabled {
+			v.Add("privateNetworkEnabled", "true")
+		}
 	}
```

**Comment by tardypad** [comment]
The issue is not only related to `DedicatedServerApi.List` function but to all the functions which accepts a `args ...interface{}` parameter.

To explain the issue with the above example of `DedicatedServerApi.List`, it is currently impossible to send a request with only a `site` parameter for example.

Since this parameter is expected to be in the 5th position, we have to specify before "empty" parameters. But this then results in a request with all the parameters being added to the request `?offset=""&limit=""&macAddress=""&ip=""&site=AMS-01` which will have a different behavior than what we want to send `?site=AMS-01`

**Comment by tardypad** [comment]
The solution proposed above is unfortunately not really solving the issue since there it is impossible to send a request with only`privateNetworkCapable=false` for example
(also the signature of the function should have been `List(opts ListOptions)` instead of `List(opts ...ListOptions)`)

**Comment by tardypad** [comment]
I found two options which I think could be valid solutions

### Option 1

Don't hardcode the parameters in the SDK and require the client to send only the list of parameters it needs.

`func (dsa DedicatedServerApi) List(args map[string]string)`

```
params = map[string]string{
	"site": "AMS-01",
	"privateNetworkCapable": "false",
}
DedicatedServerApi{}.List(params)
```

This makes the SDK very simple as there's no need to hardcode and maintain over time a list of parameters for each request.

As a downside, it requires the developer to rely a bit more on the API doc to figure out the list of parameters accepted and how to send them (boolean -> "true"/"false"), as there won't be any word completion in the editor or compilation check for them.

But to me, checking the API doc is always needed anyway because even now there is no description of what each parameter do precisely (it would need to be added as a go documentation but then we end up copy pasting the whole API doc in the SDK again).

### Option 2

Similar to the option proposed initially but each field needs to be an pointer so that it can be `nil` to indicate its absence.

```
type ListOptions struct {
	OffSet *int
	Limit *int
	IP *string
	MacAddress *string
	Site *string
	PrivateRackID *string
	PrivateNetworkCapable *bool
	PrivateNetworkEnabled *bool
}
```

The aws-sdk-go seems to be doing something similar (see for example https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#UploadInput) and hetzner too (see for example https://github.com/hetznercloud/hcloud-go/blob/main/hcloud/server.go#L306)

But then in usage it gets more complex because calling it the following way is **not** allowed as we can't take the address of a constant

```
opts = ListOptions{
	Site: &"AMS-01",
	PrivateNetworkCapable: &false,
}
DedicatedServerApi{}.List(opts)
```

so the variable needs to be defined beforehand like

```
site = "AMS-01"
pnCapable = false
opts = ListOptions{
	Site: &site,
	PrivateNetworkCapable: &pnCapable,
}
```

or there must be some wrapper around the types (like AWS is doing https://github.com/aws/aws-sdk-go/blob/main/aws/convert_types.go#L6)
```
s3manager.UploadInput {
	Key: aws.String("key"),
	Bucket: aws.String("bucket"),
}
```

**Comment by majidkarimizadeh** [comment]
Hello @tardypad @msslr, and thanks for reporting this issue and came up with the solution!
Having multiple arguments of different types and lengths for the `list` function and similar ones was a temporary solution, and now it's good to decide about the upcoming changes and see what direction we want to go with this!
I appreciate the 2 options which @tardypad provided as a solution! 

The downside of the first option as @tardypad mentioned is not clear to use (always needed to check `api-docs`) which is not the goal of this SDK at the moment! and for the second option, for now I would not prefer to add more complexity to just define arguments! 

I came up with a similar thing which still need some consideration! For `List` function (and similar) of `DedicatedServerApi` we can do:

```
import "github.com/google/go-querystring/query"

type DedicatedServerListOption struct {
	Offset                int    `url:"offset"`
	Limit                 int    `url:"limit"`
	Ip                    string `url:"ip"`
	MacAddress            string `url:"macAddress"`
	Site                  string `url:"site"`
	PrivateRackId         string `url:"privateRackId"`
	PrivateNetworkCapable bool   `url:"privateNetworkCapable"`
	PrivateNetworkEnabled bool   `url:"privateNetworkEnabled"`
}

func (dsa DedicatedServerApi) List(listOption ...DedicatedServerListOption) (*DedicatedServers, error) {
	queryValue := getQueryStringByOption(listOption)
	path := dsa.getPath("/servers?" + queryValue)
	result := &DedicatedServers{}
	if err := doRequest(http.MethodGet, path, result); err != nil {
		return nil, err
	}
	return result, nil
}

func getQueryStringByOption(option ...interface{}) string {
	if len(option) == 0 {
		return ""
	}
	q, err := query.Values(option[0])
	if err != nil {
		return ""
	}
	return q.Encode()
}
```

Pros:

1. It's an optional parameter! In case of need, you can pass the struct as argument!
2. the data types and the names of the attributes are documented, and it's easy to use for developers!

Cons:
1. Hard to maintain (change in API, long naming for option structs)
2. Allowing `List` function to receive more than 1 parameter, which ATM I think is better than passing `nil` or empty struct when we don't want to pass anything!

I would like to know your option about this solution, so we can decide next steps!

Thanks @tardypad @msslr

**Comment by tardypad** [comment]
Unfortunately the new proposed solution has the same issue as the initial one: when the struct is created all the fields are initialized with their default values and they end up in the query parameters.

To confirm it, I have built the code and tried it.

The code above is not correct, something seems wrong with the use of variadic functions.
Here is the simpler code I tried
```
type DedicatedServerListOption struct {
	Offset                int    `url:"offset"`
	Limit                 int    `url:"limit"`
	Ip                    string `url:"ip"`
	MacAddress            string `url:"macAddress"`
	Site                  string `url:"site"`
	PrivateRackId         string `url:"privateRackId"`
	PrivateNetworkCapable bool   `url:"privateNetworkCapable"`
	PrivateNetworkEnabled bool   `url:"privateNetworkEnabled"`
}

func (dsa DedicatedServerApi) List(listOption DedicatedServerListOption) (*DedicatedServers, error) {
	q, err := query.Values(listOption)
	if err != nil {
		return nil, err
	}

	path := dsa.getPath("/servers?" + q.Encode())
	result := &DedicatedServers{}
	if err := doRequest(http.MethodGet, path, result); err != nil {
		return nil, err
	}
	return result, nil
}
```

Which I've then used with the following call
```
result, err := LSW.DedicatedServerApi{}.List(LSW.DedicatedServerListOption{
	Offset: 0,
	Limit:  20,
})
```

Monitoring the call made this is what I see
`https://api.leaseweb.com/bareMetals/v2/servers?ip=&limit=20&macAddress=&offset=0&privateNetworkCapable=false&privateNetworkEnabled=false&privateRackId=&site=`

**Comment by tardypad** [comment]
Completed in https://github.com/LeaseWeb/leaseweb-go-sdk/pull/83

**Comment by msslr** [comment]
Thank you to everyone who contributed to resolving this issue. We have fixed it with the pull request [83](https://github.com/LeaseWeb/leaseweb-go-sdk/pull/83) and I closed this issue now. If any further issues arise, please don't hesitate to open a new one. Thanks again.
